[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.deploy]
startCommand = "npm run start:prod"
